import "@/styles/globals.css";
import Navbar from "@/components/shared/Navbar";
import { Providers } from "./Providers";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Blog App",
  description: "Generated by create Blog app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
